
from django.conf import settings

DEFAULT_WIDTH = getattr(settings, 'GOOGLEMAPS_DEFAULT_WIDTH', 300)
DEFAULT_HEIGHT = getattr(settings, 'GOOGLEMAPS_DEFAULT_HEIGHT', 300)

DEFAULT_LAT = getattr(settings, 'GOOGLEMAPS_DEFAULT_LAT', 50.4300647)
DEFAULT_LNG = getattr(settings, 'GOOGLEMAPS_DEFAULT_LNG', 30.5201912)

API_KEY="ABQIAAAAHlfPgw6eJbMj8hZjhN505BSInu9LSqOUWWjDwkfwomsCHQBfKRSMUSRPuAVY8FAYIDgjqDYRlGm48A"
